### ISSUE TITLE
SynEdit Invisible at Designtime in XE

### ISSUE THREAD

**Issue by Memnarch** [SynEdit/SynEdit#38] opened 2016-07-15 13:56 UTC
Just downloaded the current version and installed it into my XE and opened an existing project where i use SynEdit. Compiles and runs fine. However at designtime after the first click on the SynEdit, it becomes invisible and is only visible when i drag the SynEdit across the form.

I don't know but maybe this has something to do with the Paintlock?

**Comment by CWBudde** [comment] 2016-07-15 14:38
I can confirm this behaviour under XE2 as well. However, it doesn't seem to be related to the paintlock recently added by me.
Also, it seems to be only related to the design time as the same operations do not seem to affect the runtime. However, it seem to affect the IDE as menus don't seem to draw either until a click on the TSynEdit component.

**Comment by uschuster** [comment] 2016-07-16 08:53
Check if the behavior disappears when changing line 1548 in SynEdit.pas from

```Delphi
      if CheckWin32Version(5, 1) then
```

to

```Delphi
      if not (csDesigning in ComponentState) and CheckWin32Version(5, 1) then
```

**Comment by Memnarch** [comment] 2016-07-16 23:45
Thanks, i'll try that out on monday when i am at work again.

**Comment by CWBudde** [comment] 2016-07-17 13:29
Works on my machine

**Comment by Memnarch** [comment] 2016-07-18 06:14
works here aswell.

**Comment by uschuster** [comment] 2016-07-23 11:02
I have committed the fix.

**Closed by uschuster** 2016-07-23 11:02 UTC
